import argparse
import csv
import time
from collections import Counter
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from core.models import Movie


class Command(BaseCommand):
    help = (
        "Import manually reviewed TMDb IDs from a CSV generated by "
        "export_movies_without_tmdb. Dry-run by default; use --apply to update Movie.tmdb_id."
    )

    DEFAULT_INPUT = "tmdb_exports/movies_without_tmdb_id.csv"
    DEFAULT_REPORT = "tmdb_exports/manual_tmdb_import_report.csv"
    DEFAULT_BATCH_SIZE = 500
    REPORT_FIELDNAMES = [
        "database_id",
        "type",
        "title_en",
        "title_es",
        "year",
        "imdb_id",
        "old_tmdb_id",
        "requested_tmdb_id",
        "status",
        "reason",
    ]
    REQUIRED_COLUMNS = {"database_id", "current_tmdb_id"}
    OPTIONAL_TRACE_COLUMNS = ("type", "title_en", "title_es", "year", "imdb_id")

    def add_arguments(self, parser):
        parser.add_argument(
            "--input",
            default=self.DEFAULT_INPUT,
            help=f"Input CSV path. Defaults to {self.DEFAULT_INPUT!r}.",
        )
        parser.add_argument(
            "--report",
            default=self.DEFAULT_REPORT,
            help=f"Report CSV path. Defaults to {self.DEFAULT_REPORT!r}.",
        )
        parser.add_argument(
            "--apply",
            action="store_true",
            help="Apply valid changes. Without this flag the command runs in dry-run mode.",
        )
        parser.add_argument(
            "--batch-size",
            type=self._positive_int,
            default=self.DEFAULT_BATCH_SIZE,
            help=f"Number of valid rows to process per database batch. Defaults to {self.DEFAULT_BATCH_SIZE}.",
        )
        parser.add_argument(
            "--overwrite-report",
            action="store_true",
            help="Replace the report file if it already exists.",
        )

    def handle(self, *args, **options):
        started_at = time.monotonic()
        input_path = self._resolve_path(options["input"])
        report_path = self._resolve_path(options["report"])
        apply_changes = options["apply"]
        batch_size = options["batch_size"]

        if not input_path.exists():
            raise CommandError(f"Input file does not exist: {input_path}")
        if report_path.exists() and not options["overwrite_report"]:
            raise CommandError(
                f"Report file already exists: {report_path}. Use --overwrite-report to replace it."
            )

        self.stdout.write(f"Input: {input_path}")
        self.stdout.write(f"Report: {report_path}")
        self.stdout.write(f"Mode: {'apply' if apply_changes else 'dry-run'}")
        self.stdout.write(f"Batch size: {batch_size}")

        duplicate_info = self._scan_duplicate_database_ids(input_path)
        report_path.parent.mkdir(parents=True, exist_ok=True)

        counters = Counter()
        seen_valid_database_ids = set()
        batch = []

        with input_path.open("r", encoding="utf-8-sig", newline="") as input_file, report_path.open(
            "w", encoding="utf-8-sig", newline=""
        ) as report_file:
            reader = csv.DictReader(input_file)
            self._validate_columns(reader.fieldnames)
            writer = csv.DictWriter(report_file, fieldnames=self.REPORT_FIELDNAMES)
            writer.writeheader()

            for row in reader:
                counters["rows_read"] += 1
                parsed = self._parse_row(row)

                if parsed["status"] is not None:
                    counters[parsed["status"]] += 1
                    writer.writerow(self._report_row(row, "", parsed["tmdb_id_raw"], parsed["status"], parsed["reason"]))
                    continue

                database_id = parsed["database_id"]
                requested_tmdb_id = parsed["requested_tmdb_id"]
                duplicate = duplicate_info.get(database_id)

                if duplicate and duplicate["conflict"]:
                    counters["duplicate_database_id"] += 1
                    writer.writerow(
                        self._report_row(
                            row,
                            "",
                            requested_tmdb_id,
                            "duplicate_database_id",
                            "database_id appears with different current_tmdb_id values; skipped safely",
                        )
                    )
                    continue

                if database_id in seen_valid_database_ids:
                    counters["duplicate_database_id"] += 1
                    writer.writerow(
                        self._report_row(
                            row,
                            "",
                            requested_tmdb_id,
                            "duplicate_database_id",
                            "duplicate row with the same current_tmdb_id; already processed once",
                        )
                    )
                    continue

                seen_valid_database_ids.add(database_id)
                batch.append((row, database_id, requested_tmdb_id))
                if len(batch) >= batch_size:
                    self._process_batch(batch, writer, counters, apply_changes)
                    batch = []

            if batch:
                self._process_batch(batch, writer, counters, apply_changes)

        elapsed = time.monotonic() - started_at
        assigned_key = "assigned" if apply_changes else "would_assign"
        replaced_key = "replaced" if apply_changes else "would_replace"
        updated_total = counters["assigned"] + counters["replaced"]

        self.stdout.write(self.style.SUCCESS("Manual TMDb import finished."))
        self.stdout.write(f"Filas leídas: {counters['rows_read']}")
        self.stdout.write(f"Filas vacías ignoradas: {counters['empty_tmdb_id']}")
        self.stdout.write(
            f"Filas con ID inválido: {counters['invalid_database_id'] + counters['invalid_tmdb_id']}"
        )
        self.stdout.write(f"Registros válidos encontrados: {counters['valid_found']}")
        self.stdout.write(f"Nuevos TMDb ID {'asignados' if apply_changes else 'por asignar'}: {counters[assigned_key]}")
        self.stdout.write(f"TMDb ID {'reemplazados' if apply_changes else 'por reemplazar'}: {counters[replaced_key]}")
        self.stdout.write(f"Registros ya aplicados: {counters['already_applied']}")
        self.stdout.write(f"Duplicados: {counters['duplicate_database_id']}")
        self.stdout.write(f"No encontrados: {counters['movie_not_found']}")
        self.stdout.write(f"Errores: {counters['error']}")
        self.stdout.write(f"Total actualizado: {updated_total}")
        self.stdout.write(f"Reporte: {report_path}")
        self.stdout.write(f"Duración aproximada: {elapsed:.2f}s")

    @staticmethod
    def _resolve_path(path):
        resolved = Path(path).expanduser()
        if not resolved.is_absolute():
            resolved = Path.cwd() / resolved
        return resolved.resolve()

    @classmethod
    def _positive_int(cls, value):
        try:
            parsed = int(value)
        except (TypeError, ValueError) as exc:
            raise argparse.ArgumentTypeError("--batch-size must be a positive integer.") from exc
        if parsed <= 0:
            raise argparse.ArgumentTypeError("--batch-size must be a positive integer.")
        return parsed

    @classmethod
    def _validate_columns(cls, fieldnames):
        if not fieldnames:
            raise CommandError("Input CSV has no header row.")
        missing = cls.REQUIRED_COLUMNS.difference(fieldnames)
        if missing:
            raise CommandError(f"Input CSV is missing required columns: {', '.join(sorted(missing))}")

    def _scan_duplicate_database_ids(self, input_path):
        seen = {}
        duplicates = {}
        with input_path.open("r", encoding="utf-8-sig", newline="") as input_file:
            reader = csv.DictReader(input_file)
            self._validate_columns(reader.fieldnames)
            for row in reader:
                tmdb_id_raw = (row.get("current_tmdb_id") or "").strip()
                if not tmdb_id_raw:
                    continue
                database_id = self._parse_positive_int(row.get("database_id"))
                requested_tmdb_id = self._parse_positive_int(tmdb_id_raw)
                if database_id is None or requested_tmdb_id is None:
                    continue
                if database_id not in seen:
                    seen[database_id] = requested_tmdb_id
                    continue
                info = duplicates.setdefault(database_id, {"first_tmdb_id": seen[database_id], "conflict": False})
                if seen[database_id] != requested_tmdb_id:
                    info["conflict"] = True
        return duplicates

    def _parse_row(self, row):
        tmdb_id_raw = (row.get("current_tmdb_id") or "").strip()
        if not tmdb_id_raw:
            return {
                "status": "empty_tmdb_id",
                "reason": "current_tmdb_id is empty",
                "tmdb_id_raw": tmdb_id_raw,
            }

        database_id = self._parse_positive_int(row.get("database_id"))
        if database_id is None:
            return {
                "status": "invalid_database_id",
                "reason": "database_id is not a positive integer",
                "tmdb_id_raw": tmdb_id_raw,
            }

        requested_tmdb_id = self._parse_positive_int(tmdb_id_raw)
        if requested_tmdb_id is None:
            return {
                "status": "invalid_tmdb_id",
                "reason": "current_tmdb_id is not a positive integer",
                "tmdb_id_raw": tmdb_id_raw,
            }

        return {
            "status": None,
            "database_id": database_id,
            "requested_tmdb_id": requested_tmdb_id,
            "tmdb_id_raw": tmdb_id_raw,
        }

    @staticmethod
    def _parse_positive_int(value):
        try:
            parsed = int(str(value).strip())
        except (TypeError, ValueError):
            return None
        if parsed <= 0:
            return None
        return parsed

    def _process_batch(self, batch, writer, counters, apply_changes):
        movie_ids = [database_id for _, database_id, _ in batch]
        movies = Movie.objects.in_bulk(movie_ids)
        movies_to_update = []
        update_status_by_id = {}
        report_entries = []

        for row, database_id, requested_tmdb_id in batch:
            movie = movies.get(database_id)
            if movie is None:
                counters["movie_not_found"] += 1
                report_entries.append(
                    self._report_row(row, "", requested_tmdb_id, "movie_not_found", "Movie does not exist")
                )
                continue

            counters["valid_found"] += 1
            old_tmdb_id = movie.tmdb_id
            if old_tmdb_id == requested_tmdb_id:
                counters["already_applied"] += 1
                report_entries.append(
                    self._report_row(row, old_tmdb_id, requested_tmdb_id, "already_applied", "Movie already has this tmdb_id")
                )
                continue

            if old_tmdb_id in (None, ""):
                status = "assigned" if apply_changes else "would_assign"
                reason = "tmdb_id assigned" if apply_changes else "tmdb_id would be assigned"
            else:
                status = "replaced" if apply_changes else "would_replace"
                reason = "tmdb_id replaced" if apply_changes else "tmdb_id would be replaced"

            counters[status] += 1
            report_entries.append(self._report_row(row, old_tmdb_id, requested_tmdb_id, status, reason))
            if apply_changes:
                movie.tmdb_id = requested_tmdb_id
                movies_to_update.append(movie)
                update_status_by_id[movie.id] = status

        if apply_changes and movies_to_update:
            try:
                with transaction.atomic():
                    Movie.objects.bulk_update(movies_to_update, ["tmdb_id"])
            except Exception as exc:  # Defensive per-batch failure reporting; continue with later batches.
                counters["error"] += len(movies_to_update)
                failed_ids = {movie.id for movie in movies_to_update}
                for failed_status in update_status_by_id.values():
                    counters[failed_status] -= 1
                report_entries = [entry for entry in report_entries if int(entry["database_id"] or 0) not in failed_ids]
                for row, database_id, requested_tmdb_id in batch:
                    if database_id in failed_ids:
                        report_entries.append(
                            self._report_row(row, "", requested_tmdb_id, "error", f"bulk_update failed: {exc}")
                        )

        for entry in report_entries:
            writer.writerow(entry)

    def _report_row(self, source_row, old_tmdb_id, requested_tmdb_id, status, reason):
        report_row = {field: "" for field in self.REPORT_FIELDNAMES}
        report_row["database_id"] = source_row.get("database_id", "")
        for column in self.OPTIONAL_TRACE_COLUMNS:
            report_row[column] = source_row.get(column, "")
        report_row["old_tmdb_id"] = "" if old_tmdb_id is None else old_tmdb_id
        report_row["requested_tmdb_id"] = requested_tmdb_id
        report_row["status"] = status
        report_row["reason"] = reason
        return report_row
