# Generated by Django 6.0.2 on 2026-03-01 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rating_unique_rating_per_user_per_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐⭐'), (3, '3 ⭐⭐⭐'), (4, '4 ⭐⭐⭐⭐'), (5, '5 ⭐⭐⭐⭐⭐')]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
