# Generated by Django 6.0.2 on 2026-03-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐'), (6, '6 ⭐'), (7, '7 ⭐'), (8, '8 ⭐'), (9, '9 ⭐'), (10, '10 ⭐')]),
        ),
    ]
