# Generated by Django 6.0.2 on 2026-03-09 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_rating_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_english', models.CharField(max_length=255)),
                ('title_spanish', models.CharField(blank=True, max_length=255, null=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('cast_members', models.TextField(blank=True, null=True)),
                ('external_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
