# Generated by Codex

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_commentreaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyRecommendationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("items_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-week_start", "-id"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyRecommendationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                ("weekly_score", models.DecimalField(decimal_places=3, max_digits=6)),
                ("week_ratings_count", models.PositiveIntegerField(default=0)),
                (
                    "week_ratings_sum",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_recommendation_items",
                        to="core.movie",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.weeklyrecommendationsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="weeklyrecommendationsnapshot",
            constraint=models.UniqueConstraint(
                fields=("week_start", "week_end"),
                name="unique_weekly_recommendation_snapshot_window",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyrecommendationitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "position"),
                name="unique_weekly_recommendation_position_per_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyrecommendationitem",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "movie"),
                name="unique_weekly_recommendation_movie_per_snapshot",
            ),
        ),
    ]
