# Generated by Codex on 2026-05-06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_movie_full_text_search"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movie",
            name="movie_genre_search_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="movie_type_search_trgm_idx",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genre_search",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="type_search",
        ),
    ]
