# Generated by Django 6.0.4 on 2026-08-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_alter_usernotification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="videocomment",
            name="orientation_timeline",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
