# Generated by Django 6.0.4 on 2026-08-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_videocomment_orientation_timeline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videocomment",
            name="orientation_timeline",
        ),
    ]
