# Generated by Django 6.0.4 on 2026-08-14 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_videocommentreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="video_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.videocomment",
            ),
        ),
        migrations.AlterField(
            model_name="usernotification",
            name="type",
            field=models.CharField(
                choices=[
                    ("private_message", "Private message"),
                    ("public_comment_reaction", "Public comment reaction"),
                    ("private_comment_reaction", "Private comment reaction"),
                    ("friend_request_received", "Friend request received"),
                    ("video_comment_reaction", "Video comment reaction"),
                ],
                max_length=40,
            ),
        ),
    ]
