# Generated by Django 6.0.4 on 2026-08-14 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_usernotification_video_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="usernotification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("video_comment__isnull", False)),
                fields=("recipient", "actor", "video_comment", "type"),
                name="unique_user_notification_per_actor_video_type",
            ),
        ),
    ]
