# Generated by Django 6.0.4 on 2026-08-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_usernotification_unique_user_notification_per_actor_video_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="detail_movie_tour_current_step",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="detail_movie_tour_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="detail_movie_tour_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="profile",
            name="feed_tour_current_step",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="feed_tour_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="feed_tour_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_feed_tour_current_step",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_feed_tour_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("skipped", "Skipped"),
                ],
                default="pending",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_feed_tour_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
