# Generated by Django 6.0.4 on 2026-08-30 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_profile_detail_movie_tour_current_step_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Servicio técnico"),
                            ("commercial", "Comercial"),
                            ("requests_suggestions", "Peticiones y sugerencias"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Servicio técnico"),
                            ("commercial", "Comercial"),
                            ("requests_suggestions", "Peticiones y sugerencias"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=1500)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contact_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
