# Generated by Django 6.0.4 on 2026-09-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_pendinguserregistration_terms_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
