# Generated by Django 6.0.4 on 2026-10-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_alter_movie_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="streaming_country",
            field=models.CharField(
                choices=[
                    ("AE", "United Arab Emirates"),
                    ("AR", "Argentina"),
                    ("AU", "Australia"),
                    ("BO", "Bolivia"),
                    ("BZ", "Belice"),
                    ("CA", "Canadá"),
                    ("CL", "Chile"),
                    ("CO", "Colombia"),
                    ("CR", "Costa Rica"),
                    ("CU", "Cuba"),
                    ("DE", "Germany"),
                    ("DO", "República Dominicana"),
                    ("EC", "Ecuador"),
                    ("ES", "España"),
                    ("GT", "Guatemala"),
                    ("HN", "Honduras"),
                    ("MX", "México"),
                    ("NI", "Nicaragua"),
                    ("PA", "Panamá"),
                    ("PE", "Perú"),
                    ("PR", "Puerto Rico"),
                    ("PY", "Paraguay"),
                    ("SV", "El Salvador"),
                    ("UK", "Reino Unido"),
                    ("US", "Estados Unidos"),
                    ("UY", "Uruguay"),
                    ("VE", "Venezuela"),
                ],
                default="CO",
                max_length=2,
            ),
        ),
    ]
