from django.urls import path
from .views import (
    AppBrandingView, UserSearchView, UserProfileView, MeView, MePersonalDataView, FollowToggleView, UserFollowersListView, UserFollowingListView,
    MeFollowingListView, UserFriendsListView,
    FriendshipRequestCreateView, FriendshipRequestAcceptView, FriendshipRequestRejectView,
    FriendshipRequestCancelView, FriendshipDeleteView, FriendsListView,
    FriendMentionListView,
    SocialFollowingListView, SocialFriendsListView,
    ReceivedFriendshipRequestsView, SentFriendshipRequestsView,
    FeedFollowingView, DiscoverView, PublicCommentsFeedView, ProfileFeedActivityView, UserProfileActivityView, PostListCreateView, PostDetailView, PostRatingView,
    UserPostsListView, MovieCommentsListCreateView, PostCommentsListCreateView, CommentDetailView, CommentReactionView, RegisterView,
    DirectedCommentsListView, ReceivedDirectedCommentsView, SentDirectedCommentsView, MeMessagesView, MeMessagesSummaryView, MeMessagesMarkAsReadView,
    MeNotificationsView, MeNotificationsMarkReadView, MeNotificationsMarkAllReadView, MeNotificationsMarkReadBatchView,
    MeNotificationsMarkContextReadView,
    MovieListView, MovieDetailView, MovieDirectedCommentsListView, DirectedConversationMessagesView, MovieRatingView, MeTasteProfileView, FeedMoviesView, WeeklyRecommendationsView,
    MyMovieListView, MovieListToggleView, MyMovieRecommendationsView, MovieRecommendationToggleView,
    ProfileFavoritesView, UserProfileFavoritesView, ProfileFavoriteSlotDetailView, ProfilePrivacyView, ProfilePrivacyBlockedUsersView,
    ProfilePrivacyBlockedUserDetailView,
)

urlpatterns = [
    path("branding/", AppBrandingView.as_view(), name="app-branding"),
    path("register/", RegisterView.as_view(), name="register"),
    path("users/search/", UserSearchView.as_view(), name="user-search"),
    path("users/search", UserSearchView.as_view(), name="user-search-no-slash"),
    path("users/<str:username>/", UserProfileView.as_view(), name="user-profile"),
    path("users/<str:username>/posts/", UserPostsListView.as_view(), name="user-posts"),
    path("me/", MeView.as_view(), name="me"), 
    path("me/personal-data/", MePersonalDataView.as_view(), name="me-personal-data"),
    path("me/following/", MeFollowingListView.as_view(), name="me-following"),
    path("me/taste-profile/", MeTasteProfileView.as_view(), name="me-taste-profile"),
    path("me/movie-list/", MyMovieListView.as_view(), name="me-movie-list"),
    path("me/movie-recommendations/", MyMovieRecommendationsView.as_view(), name="me-movie-recommendations"),
    path("me/messages/", MeMessagesView.as_view(), name="me-messages"),
    path("me/messages/summary/", MeMessagesSummaryView.as_view(), name="me-messages-summary"),
    path("me/messages/mark-as-read/", MeMessagesMarkAsReadView.as_view(), name="me-messages-mark-as-read"),
    path("me/notifications/", MeNotificationsView.as_view(), name="me-notifications"),
    path("me/notifications/mark-read/", MeNotificationsMarkReadView.as_view(), name="me-notifications-mark-read"),
    path("notifications/mark-all-read/", MeNotificationsMarkAllReadView.as_view(), name="notifications-mark-all-read"),
    path("notifications/mark-read-batch/", MeNotificationsMarkReadBatchView.as_view(), name="notifications-mark-read-batch"),
    path("notifications/mark-context-read/", MeNotificationsMarkContextReadView.as_view(), name="notifications-mark-context-read"),
    path("profile/favorites/", ProfileFavoritesView.as_view(), name="profile-favorites"),
    path("profile/favorites/<int:slot>/", ProfileFavoriteSlotDetailView.as_view(), name="profile-favorite-slot"),
    path("profile/privacy/", ProfilePrivacyView.as_view(), name="profile-privacy"),
    path("profile/privacy/blocked-users/", ProfilePrivacyBlockedUsersView.as_view(), name="profile-privacy-blocked-users"),
    path("profile/privacy/blocked-users/<int:user_id>/", ProfilePrivacyBlockedUserDetailView.as_view(), name="profile-privacy-blocked-user-detail"),
    path("follow/<str:username>/", FollowToggleView.as_view(), name="follow-toggle"),
    path("users/<str:username>/followers/", UserFollowersListView.as_view(), name="user-followers"),
    path("users/<str:username>/following/", UserFollowingListView.as_view(), name="user-following"),
    path("users/<str:username>/friends/", UserFriendsListView.as_view(), name="user-friends"),
    path("users/<str:username>/favorites/", UserProfileFavoritesView.as_view(), name="user-favorites"),
    path("users/<str:username>/activity/", UserProfileActivityView.as_view(), name="user-activity"),
    path("social/following/", SocialFollowingListView.as_view(), name="social-following-list"),
    path("friendships/", FriendsListView.as_view(), name="friendship-list"),
    path("friends/", FriendMentionListView.as_view(), name="friends-list"),
    path("social/friends/", SocialFriendsListView.as_view(), name="social-friends-list"),
    path("friendships/requests/received/", ReceivedFriendshipRequestsView.as_view(), name="friendship-requests-received"),
    path("friendships/requests/sent/", SentFriendshipRequestsView.as_view(), name="friendship-requests-sent"),
    path("friendships/requests/<str:username>/", FriendshipRequestCreateView.as_view(), name="friendship-request-create"),
    path("friendships/requests/<int:pk>/accept/", FriendshipRequestAcceptView.as_view(), name="friendship-request-accept"),
    path("friendships/requests/<int:pk>/reject/", FriendshipRequestRejectView.as_view(), name="friendship-request-reject"),
    path("friendships/requests/<int:pk>/cancel/", FriendshipRequestCancelView.as_view(), name="friendship-request-cancel"),
    path("friendships/<str:username>/", FriendshipDeleteView.as_view(), name="friendship-delete"),
    path("feed/", FeedFollowingView.as_view(), name="feed-following"),
    path("feed/comments/public/", PublicCommentsFeedView.as_view(), name="public-comments-feed"),
    path("profile-feed/activity/", ProfileFeedActivityView.as_view(), name="profile-feed-activity"),
    path("discover/", DiscoverView.as_view(), name="discover"),
    path("posts/", PostListCreateView.as_view(), name="post-list-create"),
    path("posts/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path("posts/<int:pk>/rating/", PostRatingView.as_view(), name="post-rating"),
    path("movies/", MovieListView.as_view(), name="movie-list"),
    path("movies/<int:pk>/", MovieDetailView.as_view(), name="movie-detail"),
    path("feed/movies/", FeedMoviesView.as_view(), name="feed-movies"),
    path("feed/weekly-recommendations/", WeeklyRecommendationsView.as_view(), name="weekly-recommendations"),
    path("movies/weekly/", WeeklyRecommendationsView.as_view(), name="movies-weekly"),
    path("movies/<int:pk>/rating/", MovieRatingView.as_view(), name="movie-rating"),
    path("movies/<int:pk>/list/", MovieListToggleView.as_view(), name="movie-list-toggle"),
    path("movies/<int:pk>/recommendation/", MovieRecommendationToggleView.as_view(), name="movie-recommendation-toggle"),
    path("movies/<int:pk>/comments/", MovieCommentsListCreateView.as_view(), name="movie-comments"),
    path("movies/<int:pk>/comments/directed/", MovieDirectedCommentsListView.as_view(), name="movie-directed-comments"),
    path("movies/<int:pk>/comments/directed/conversations/<str:username>/messages/", DirectedConversationMessagesView.as_view(), name="movie-directed-conversation-messages"),
    path("comments/directed/", DirectedCommentsListView.as_view(), name="directed-comments"),
    path("comments/directed/received/", ReceivedDirectedCommentsView.as_view(), name="directed-comments-received"),
    path("comments/directed/sent/", SentDirectedCommentsView.as_view(), name="directed-comments-sent"),
    path("posts/<int:pk>/comments/", PostCommentsListCreateView.as_view(), name="post-comments"),
    path("comments/<int:pk>/", CommentDetailView.as_view(), name="comment-detail"),
    path("comments/<int:pk>/reaction/", CommentReactionView.as_view(), name="comment-reaction"),
]
