# Generated by Django 6.0.4 on 2026-10-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0072_movierecommendationhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
            ],
            options={
                'verbose_name': 'Generar reportes',
                'verbose_name_plural': 'Generar reportes',
                'permissions': [('can_view_reports', 'Puede visualizar reportes'), ('can_export_reports', 'Puede exportar reportes')],
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('core.profile',),
        ),
    ]
